### ISSUE TITLE
Support email notifications

### ISSUE THREAD

**Issue by mhbates** [linuxserver/docker-fail2ban#5] opened 2022-09-11 22:57 UTC
It would be nice to be able to configure email notifications.

**Comment by nemchik** [comment] 2022-09-11 23:45
Have you tried? Was there an error?

You should be able to, unless we're missing a package or something.

**Comment by mhbates** [comment] 2022-09-12 01:35
Sorry, I guess what I meant was I wasn't sure how to actually configure the email sending settings. That's done within the container, no? Where is that set up in the container? And I'm referring to external email, SMTP, not internal.

**Comment by nemchik** [comment] 2022-09-12 20:40
You could use the included configs for `sendmail` or `apprise`. You'll need to look at the files in the `actions.d` folder and read the comments at the top. Keep in mind that many of the configs weren't created by LSIO, and are part of the fail2ban package itself.

I'm going to close this issue since it's a configuration question, and not a bug with the container image.

**Closed as completed by nemchik** 2022-09-12 20:40 UTC

**Comment by mhbates** [comment] 2022-09-12 20:49
Thanks. I'll dig around in the container for the sendmail config to set up the SMTP relay. I'm thinking I can just volume mount that and do it that way.
